name: Block Edits to Reg Sync Workflow

on:
  pull_request_target:
    paths:
      - '.github/workflows/regsync.yaml'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if changes are detected
        run: exit 1