name: Pull Request Target Workflow

on:
  pull_request_target:

jobs:
  print-details:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout base branch
      uses: actions/checkout@v3

    - name: Check out PR
      run: gh pr checkout ${{ github.event.pull_request.number }}

    - name: Print branch details
      run: |
        echo "Workflow Branch: ${{ github.ref }}"
        echo "Checked out branch: $(git rev-parse --abbrev-ref HEAD)"
        echo "This workflow has the pull_request trigger"
