name: Label and Approval Check Workflow

on:
  pull_request_target:
    types:
      - labeled

jobs:
  onLabelAndApproval:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'regsync-ready'
    steps:
      - name: Check if PR is approved
        id: check-approval
        run: |
          IS_APPROVED=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews --jq '[.[] | select(.state == "APPROVED")] | length')
          if [[ "$IS_APPROVED" -gt 0 ]]; then
            echo "::set-output name=approved::true"
          else
            echo "::set-output name=approved::false"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run if approved
        if: steps.check-approval.outputs.approved == 'true'
        run: echo "Label 'regsync-ready' was added and the PR is approved!"
