name: Test Trigger

on:
  pull_request_review:

jobs:
  onApproval:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Execute steps for approved PR
        run: echo "PR was approved!"

